# Generated by Django 5.2.4 on 2025-07-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SortApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='escudo',
            field=models.ImageField(upload_to='escudos/'),
        ),
    ]
