# Generated by Django 5.2.4 on 2025-07-17 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SortApp', '0002_alter_time_escudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogadores', to='SortApp.time'),
        ),
    ]
