# Generated by Django 5.2.4 on 2025-12-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SortApp', '0003_alter_jogador_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='grupo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
