# Generated by Django 5.2.4 on 2025-12-20 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SortApp', '0004_time_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('time_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_como_a', to='SortApp.time')),
                ('time_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_como_b', to='SortApp.time')),
            ],
        ),
    ]
